# Generated by Django 5.2.6 on 2025-10-01 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del paciente (UUID)', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre completo del paciente', max_length=255)),
                ('rut', models.CharField(blank=True, help_text='Documento de identidad (RUT/DNI). Conviene cifrar para proteger PII', max_length=20, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del paciente', null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto telefónico. Conviene cifrar', max_length=20, null=True)),
                ('correo', models.EmailField(blank=True, help_text='Correo electrónico de contacto. Conviene cifrar', max_length=255, null=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección de residencia. Conviene cifrar', null=True)),
                ('estado', models.CharField(blank=True, help_text='Estado del paciente: EN_ESPERA o OPERADO', max_length=20, null=True)),
                ('fecha_cambio_estado', models.DateTimeField(blank=True, help_text='Fecha en que el paciente cambió de estado', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro del paciente')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del registro')),
                ('eliminado_en', models.DateTimeField(blank=True, help_text='Fecha de borrado lógico (nullable). Permite auditoría e histórico', null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó el registro (FK a usuarios.id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el registro (FK a usuarios.id)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'pacientes',
            },
        ),
    ]
