# Generated by Django 5.2.6 on 2025-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, default='EN_ESPERA', help_text='Estado del paciente: EN_ESPERA o OPERADO', max_length=20),
        ),
    ]
