# Generated by Django 5.2.6 on 2025-10-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_paciente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, choices=[('EN_ESPERA', 'En Espera'), ('OPERADO', 'Operado')], default='EN_ESPERA', help_text='Estado del paciente: EN_ESPERA o OPERADO', max_length=20),
        ),
    ]
