# Generated by Django 5.2.6 on 2025-10-19 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_paciente_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EjeCriterio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CLINICO', 'Clínico'), ('SOCIAL', 'Social')], help_text='Tipo de eje: CLINICO o SOCIAL', max_length=20)),
                ('descripcion', models.TextField(help_text='Nombre del eje, solo enunciado general')),
                ('orden', models.IntegerField(blank=True, help_text='Orden en que debe desplegarse el eje en la interfaz', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del eje de criterios')),
                ('actualizado_en', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización del eje')),
                ('actualizado_por', models.ForeignKey(blank=True, help_text='Usuario que modificó el eje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejes_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que creó el eje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ejes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Eje de criterio',
                'verbose_name_plural': 'Ejes de criterios',
                'db_table': 'ejes_criterios',
            },
        ),
    ]
