# Generated by Django 5.2.6 on 2025-10-19 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_ejecriterio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioClinico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text="Descripción del criterio clínico (ej: 'Lipoma')")),
                ('max_dias', models.IntegerField(blank=True, help_text='Tiempo máximo aplicable al criterio en días', null=True)),
                ('puntaje', models.IntegerField(blank=True, help_text='Puntaje asignado al cumplir el criterio', null=True)),
                ('orden', models.IntegerField(blank=True, help_text='Orden dentro del eje en que se debe mostrar el criterio', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterios_clinicos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterios_clinicos_creados', to=settings.AUTH_USER_MODEL)),
                ('eje', models.ForeignKey(help_text='FK hacia ejes_criterios.id', on_delete=django.db.models.deletion.CASCADE, related_name='criterios_clinicos', to='medicos.ejecriterio')),
            ],
            options={
                'verbose_name': 'Criterio clínico',
                'verbose_name_plural': 'Criterios clínicos',
                'db_table': 'criterios_clinicos',
            },
        ),
    ]
