# Generated by Django 5.2.6 on 2025-10-19 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_criterioclinico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioSocial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(help_text="Descripción del criterio social (ej: 'Jefe de hogar incapacitado')")),
                ('puntaje', models.IntegerField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterios_sociales_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criterios_sociales_creados', to=settings.AUTH_USER_MODEL)),
                ('eje', models.ForeignKey(help_text='FK hacia ejes_criterios.id', on_delete=django.db.models.deletion.CASCADE, related_name='criterios_sociales', to='medicos.ejecriterio')),
            ],
            options={
                'verbose_name': 'Criterio social',
                'verbose_name_plural': 'Criterios sociales',
                'db_table': 'criterios_sociales',
            },
        ),
        migrations.CreateModel(
            name='RangoTiempo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, help_text="Descripción del rango (ej: '3-4 meses en lista')", null=True)),
                ('dias_min', models.IntegerField(blank=True, help_text='Cantidad mínima de días en lista para aplicar el rango', null=True)),
                ('dias_max', models.IntegerField(blank=True, help_text='Cantidad máxima de días en lista para aplicar el rango', null=True)),
                ('puntaje', models.IntegerField(blank=True, help_text='Puntaje otorgado por permanencia en este rango', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rangos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rango de tiempo',
                'verbose_name_plural': 'Rangos de tiempo',
                'db_table': 'rangos_tiempo',
            },
        ),
    ]
