# Generated by Django 5.2.6 on 2025-10-19 22:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_criteriosocial_rangotiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPuntaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único del registro de historial de puntajes', primary_key=True, serialize=False)),
                ('fecha_cambio', models.DateTimeField(help_text='Fecha en que se registró el cambio de puntaje')),
                ('puntaje_inicial', models.IntegerField(blank=True, help_text='Puntaje por criterios clínicos/sociales en ese momento', null=True)),
                ('puntaje_tiempo', models.IntegerField(blank=True, help_text='Puntaje por tiempo de permanencia', null=True)),
                ('puntaje_total', models.IntegerField(blank=True, help_text='Suma de puntaje_inicial + puntaje_tiempo', null=True)),
                ('motivo_cambio', models.CharField(blank=True, choices=[('INGRESO', 'Ingreso'), ('PERMANENCIA', 'Permanencia'), ('AJUSTE_CRITERIOS', 'Ajuste de criterios'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('MANUAL', 'Manual')], help_text='Motivo del cambio', max_length=50, null=True)),
                ('paciente', models.ForeignKey(help_text='FK hacia pacientes.id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntajes', to='medicos.paciente')),
            ],
            options={
                'verbose_name': 'Historial de puntaje',
                'verbose_name_plural': 'Historial de puntajes',
                'db_table': 'historial_puntajes',
            },
        ),
    ]
