# Generated by Django 5.2.6 on 2025-10-31 14:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_historialpuntaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que modificó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(default='sinmail@ejemplo.com', help_text='Correo electrónico de contacto', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación del registro'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que creó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(default='sindirecion', help_text='Dirección de residencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='eliminado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha soft delete', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de nacimiento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(help_text='Nombre', max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(default='0', help_text='Documento de identidad (RUT/DNI)', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='0', help_text='Número de contacto telefónico', max_length=20),
            preserve_default=False,
        ),
    ]
