# Generated by Django 5.2.6 on 2025-10-31 15:51

from django.db import migrations
from django.utils import timezone

def insertar_rangos_tiempo(apps, schema_editor):
    RangoTiempo = apps.get_model('medicos', 'RangoTiempo')
    User = apps.get_model('auth', 'User')
    # Busca el usuario por username (ajusta si el nombre es diferente)
    try:
        creador = User.objects.get(username="_strik_")
    except User.DoesNotExist:
        creador = None

    datos = [
        {"descripcion": "0-2 meses", "dias_min": 0, "dias_max": 60, "puntaje": 0},
        {"descripcion": "3-4 meses", "dias_min": 61, "dias_max": 120, "puntaje": 1},
        {"descripcion": "7-8 meses", "dias_min": 181, "dias_max": 240, "puntaje": 2},
        {"descripcion": "9-10 meses", "dias_min": 241, "dias_max": 300, "puntaje": 4},
        {"descripcion": "11-12 meses", "dias_min": 301, "dias_max": 365, "puntaje": 6},
        {"descripcion": "13-14 meses", "dias_min": 366, "dias_max": 420, "puntaje": 10},
        {"descripcion": "15-16 meses", "dias_min": 421, "dias_max": 480, "puntaje": 18},
        {"descripcion": "17-18 meses", "dias_min": 481, "dias_max": 540, "puntaje": 30},
        {"descripcion": "19-20 meses", "dias_min": 541, "dias_max": 600, "puntaje": 46},
        {"descripcion": "21-22 meses", "dias_min": 601, "dias_max": 660, "puntaje": 66},
        {"descripcion": "23-24 meses", "dias_min": 661, "dias_max": 730, "puntaje": 90},
    ]
    fecha = timezone.datetime(2025, 10, 31)
    for d in datos:
        RangoTiempo.objects.create(
            descripcion=d["descripcion"],
            dias_min=d["dias_min"],
            dias_max=d["dias_max"],
            puntaje=d["puntaje"],
            creado_en=fecha,
            actualizado_en=None,
            creado_por=creador,
            actualizado_por=None
        )

class Migration(migrations.Migration):
    dependencies = [
        ('medicos', '0008_alter_paciente_actualizado_por_alter_paciente_correo_and_more'),
    ]
    operations = [
        migrations.RunPython(insertar_rangos_tiempo),
    ]