# Generated by Django 5.2.6 on 2025-11-01 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0009_insertar_rangos_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpuntaje',
            name='rango_tiempo',
            field=models.ForeignKey(blank=True, help_text='FK hacia rangos_tiempo.id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_puntajes', to='medicos.rangotiempo'),
        ),
    ]
