# Generated by Django 5.2.6 on 2025-11-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0011_insertar_ejecriterio'),
        ('medicos', '0012_insertar_criterios_clinicos'),
    ]

    operations = [
    ]
