# Generated by Django 5.2.6 on 2025-11-01 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0013_insertar_criterios_sociales'),
        ('medicos', '0013_merge_20251101_0017'),
    ]

    operations = [
    ]
