# Generated by Django 5.2.6 on 2025-11-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0014_merge_20251101_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='comentario',
            field=models.CharField(blank=True, help_text='Comentario libre sobre el paciente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], default='H', help_text='Sexo del paciente: H para hombre, M para mujer', max_length=1),
            preserve_default=False,
        ),
    ]
