# Generated by Django 5.2.6 on 2025-11-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0015_paciente_comentario_paciente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentario libre sobre el paciente', null=True),
        ),
    ]
