# Generated by Django 5.2.6 on 2025-11-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0016_alter_paciente_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='creado_en',
            field=models.DateTimeField(help_text='Fecha de creación del registro'),
        ),
    ]
