# Generated by Django 5.2.6 on 2025-11-14 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0017_alter_paciente_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(help_text='Nombre', max_length=255, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios en el nombre.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(help_text='Documento de identidad (RUT/DNI)', max_length=20),
        ),
    ]
