# Generated by Django 5.2.6 on 2025-11-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0018_alter_paciente_nombre_alter_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='correo',
            field=models.EmailField(blank=True, help_text='Correo electrónico de contacto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección de residencia', null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], help_text='Sexo del paciente: H para hombre, M para mujer', max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de contacto telefónico', max_length=20, null=True),
        ),
    ]
